baseURL = "https://example.com/"
languageCode = "en-us"
title = "Eddy Varela"
theme = "resume"

[params]
    firstName = "Eddy"
    lastName = "Varela"
    address = "Miami, FL"
    phone = "786-266-7716"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/TechChat.png"
    email = "eddy@captaincode.cc"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/eddy.varela5/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/edv1297/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "key"

[params.google.analytics]
    trackerID = "XX-123446-01"
